default: &default
  adapter: postgresql
  encoding: unicode

development:
  #<<: *default
  #database: Raffle_development
  adapter: postgresql
  database: 'd1ukai0g6o5ke9'
  username: 'ydctawskemlkbi'
  password: '33d36855f74b9e91344a439b493df271ee2c9d142b5359f03d387f2a44424d18'
  host: 'ec2-54-83-58-17.compute-1.amazonaws.com'
  port: '5432'
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: 'd1ukai0g6o5ke9'
  username: 'ydctawskemlkbi'
  password: '33d36855f74b9e91344a439b493df271ee2c9d142b5359f03d387f2a44424d18'
  host: 'ec2-54-83-58-17.compute-1.amazonaws.com'
  port: '5432'
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: 'd1ukai0g6o5ke9'
